### ISSUE TITLE
Default Spinner disappeared after creating Page Load DA in Global Page

### ISSUE THREAD

**Issue by aragorniiit** [apexutils/Change-Spinner#3]
I created a DA on Global Page load and used HTML & CSS from Custom Spinner2 in your app. 
Now I don't see default spinner when page process is working. I haven't written any code to call apex.util.showSpinner

![image](https://user-images.githubusercontent.com/30124551/59629986-28b68580-9112-11e9-8cf1-7db7b2274835.png)

**Comment by stefandobre** [comment]
Hi there!

I just tested it out again on APEX 18.2 and 19.1, and it worked just fine on page submit.

Some questions to narrow it down:

- Try running `apex.util.showSpinner('body', {fixed: true});` in the JavaScript console. Is the spinner showing?
- How long is your page process? Try adding `apex_util.pause(1);` in there, as processes which finish in under 200ms will not show any spinner, not even the default APEX one.

**Comment by aragorniiit** [comment]
apex.util.showSpinner('body', {fixed: true}); in console is showing the spinner.

My page has a Create button which opens a modal page. Modal page Create button calls page process which inserts data into custom table and branches to another page. I added apex_util.pause(1); to the page process still dont see custom spinner. When I dont customize spinner, I see default spinner upon Create button even without adding apex_util.pause(1) to the page process.

![image](https://user-images.githubusercontent.com/30124551/59691828-aed5d900-91b1-11e9-86dd-6241d6875552.png)

**Comment by stefandobre** [comment]
It seems it does indeed behave differently on a modal page.
I fixed it in version 1.1
Let me know if it works for you!

**Comment by aragorniiit** [comment]
Awesome. It works now. 
I really appreciate your time in fixing it promptly. 

![image](https://user-images.githubusercontent.com/30124551/59706780-32ea8980-91cf-11e9-8dc8-89e33d6337d7.png)
